import { HubsNetwork, HubsNetworkSchema } from '@/types/nodes';

export const hubsConfig: HubsNetwork = HubsNetworkSchema.parse({
  networkName: 'OmniFlow Planetary Mesh',
  topology: 'full-mesh',
  syncFrequencyHz: 60,
  hubs: [
    {
      id: 'hub-tyo-01',
      name: 'Tokyo Apex Node',
      tier: 'primary',
      status: 'operational',
      coordinates: {
        lat: 35.6762,
        lng: 139.6503,
        city: 'Tokyo',
        country: 'Japan',
        region: 'ap-northeast-1',
      },
      latencyMs: 14.2,
      throughputGbps: 420.5,
      activeAgents: 1420,
      uptimePercentage: 99.998,
      meshConnections: ['hub-sin-01', 'hub-sfo-01', 'hub-fra-01', 'hub-dhk-01'],
    },
    {
      id: 'hub-fra-01',
      name: 'Frankfurt Central Core',
      tier: 'primary',
      status: 'operational',
      coordinates: {
        lat: 50.1109,
        lng: 8.6821,
        city: 'Frankfurt',
        country: 'Germany',
        region: 'eu-central-1',
      },
      latencyMs: 11.8,
      throughputGbps: 580.0,
      activeAgents: 2150,
      uptimePercentage: 99.999,
      meshConnections: ['hub-sfo-01', 'hub-sin-01', 'hub-tyo-01', 'hub-dhk-01'],
    },
    {
      id: 'hub-sfo-01',
      name: 'San Francisco Bay Mesh',
      tier: 'primary',
      status: 'operational',
      coordinates: {
        lat: 37.7749,
        lng: -122.4194,
        city: 'San Francisco',
        country: 'United States',
        region: 'us-west-1',
      },
      latencyMs: 8.4,
      throughputGbps: 640.2,
      activeAgents: 3410,
      uptimePercentage: 99.995,
      meshConnections: ['hub-tyo-01', 'hub-fra-01', 'hub-sin-01', 'hub-dhk-01'],
    },
    {
      id: 'hub-sin-01',
      name: 'Singapore Equator Gateway',
      tier: 'edge',
      status: 'operational',
      coordinates: {
        lat: 1.3521,
        lng: 103.8198,
        city: 'Singapore',
        country: 'Singapore',
        region: 'ap-southeast-1',
      },
      latencyMs: 16.5,
      throughputGbps: 310.8,
      activeAgents: 980,
      uptimePercentage: 99.992,
      meshConnections: ['hub-tyo-01', 'hub-dhk-01', 'hub-fra-01', 'hub-sfo-01'],
    },
    {
      id: 'hub-dhk-01',
      name: 'Dhaka Delta Relay',
      tier: 'gateway',
      status: 'operational',
      coordinates: {
        lat: 23.8103,
        lng: 90.4125,
        city: 'Dhaka',
        country: 'Bangladesh',
        region: 'ap-south-2',
      },
      latencyMs: 22.1,
      throughputGbps: 195.4,
      activeAgents: 640,
      uptimePercentage: 99.987,
      meshConnections: ['hub-sin-01', 'hub-fra-01', 'hub-tyo-01', 'hub-sfo-01'],
    },
  ],
});
