import { TelemetryConfig, TelemetryConfigSchema } from '@/types/telemetry';

export const telemetryConfig: TelemetryConfig = TelemetryConfigSchema.parse({
  refreshIntervalMs: 2500,
  kpiPulses: [
    {
      id: 'kpi-p99-latency',
      name: 'Global Mesh Latency',
      value: 12.6,
      formattedValue: '12.6 ms',
      unit: 'ms',
      changePercentage24h: -14.8,
      targetBenchmark: 20.0,
      severity: 'optimal',
      trend: 'down',
    },
    {
      id: 'kpi-agent-throughput',
      name: 'Autonomous Throughput',
      value: 2.15,
      formattedValue: '2.15M ops/s',
      unit: 'M ops/s',
      changePercentage24h: 38.4,
      targetBenchmark: 1.5,
      severity: 'optimal',
      trend: 'up',
    },
    {
      id: 'kpi-consensus-drift',
      name: 'State Mesh Consistency',
      value: 99.999,
      formattedValue: '99.999%',
      unit: '%',
      changePercentage24h: 0.001,
      targetBenchmark: 99.99,
      severity: 'optimal',
      trend: 'stable',
    },
    {
      id: 'kpi-active-agents',
      name: 'Active Distributed Agents',
      value: 8600,
      formattedValue: '8,600 units',
      unit: 'units',
      changePercentage24h: 18.2,
      targetBenchmark: 5000,
      severity: 'optimal',
      trend: 'up',
    },
  ],
  efficiencyGains: [
    {
      category: 'Pipeline Autonomous Orchestration',
      headlineMetric: '92% Reduction in Manual Interventions',
      savingsRatio: '14.2x Faster Mean Time To Resolution (MTTR)',
      hoursAutomatedPerWeek: 1680,
      costReductionPercentage: 64.5,
      humanInterventionDrop: 92.0,
      description: 'Dynamic graph re-planning eliminates blocking deadlocks across edge compute pods.',
    },
    {
      category: 'Compute & Resource Optimization',
      headlineMetric: '43% Cloud Cost Optimization',
      savingsRatio: '$1.48M Annualized Compute Savings',
      hoursAutomatedPerWeek: 840,
      costReductionPercentage: 43.2,
      humanInterventionDrop: 88.5,
      description: 'Predictive token allocation routes batch tasks to lowest marginal cost carbon-neutral hubs.',
    },
  ],
  initialEvents: [
    {
      id: 'evt-001',
      timestamp: '2026-09-29T20:20:10.112Z',
      sourceHub: 'hub-tyo-01',
      eventCategory: 'agent_dispatch',
      message: 'Agent pool #382 synchronized state root across 4 peer hubs.',
      status: 'success',
      latencyMs: 14.1,
    },
    {
      id: 'evt-002',
      timestamp: '2026-09-29T20:20:45.342Z',
      sourceHub: 'hub-fra-01',
      eventCategory: 'pipeline_sync',
      message: 'Consensus quorum reached for workflow batch 0x9AF8.',
      status: 'success',
      latencyMs: 11.7,
    },
    {
      id: 'evt-003',
      timestamp: '2026-09-29T20:21:05.901Z',
      sourceHub: 'hub-dhk-01',
      eventCategory: 'state_transition',
      message: 'Edge gateway ingress auto-scaled to handle spike (+45 Gbps).',
      status: 'info',
      latencyMs: 21.9,
    },
    {
      id: 'evt-004',
      timestamp: '2026-09-29T20:21:28.450Z',
      sourceHub: 'hub-sfo-01',
      eventCategory: 'failover_recovery',
      message: 'Worker thread re-routed to Tokyo hub seamlessly without dropped frames.',
      status: 'success',
      latencyMs: 8.3,
    },
  ],
  initialAgentTraces: [
    {
      id: 'tr-01',
      traceId: 'trace-langgraph-8891',
      framework: 'langgraph',
      agentId: 'supervisor-router-04',
      cloudRegion: 'us-west-2',
      action: 'Dynamic Sub-Graph Handoff to Code Generator',
      promptTokens: 2410,
      completionTokens: 620,
      estimatedCostUsd: 0.0092,
      latencyMs: 312,
      confidenceScore: 0.96,
      driftVariance: 0.04,
      status: 'success',
      timestamp: '2026-10-01T21:10:00Z',
    },
    {
      id: 'tr-02',
      traceId: 'trace-crewai-4102',
      framework: 'crewai',
      agentId: 'research-critic-02',
      cloudRegion: 'europe-west3',
      action: 'Cross-Document Factuality Verification Loop',
      promptTokens: 4120,
      completionTokens: 890,
      estimatedCostUsd: 0.0164,
      latencyMs: 540,
      confidenceScore: 0.88,
      driftVariance: 0.12,
      status: 'success',
      timestamp: '2026-10-01T21:10:45Z',
    },
    {
      id: 'tr-03',
      traceId: 'trace-mcp-9912',
      framework: 'mcp',
      agentId: 'db-migration-tool',
      cloudRegion: 'ap-northeast-1',
      action: 'Model Context Protocol Query Execution',
      promptTokens: 1850,
      completionTokens: 240,
      estimatedCostUsd: 0.0048,
      latencyMs: 145,
      confidenceScore: 0.99,
      driftVariance: 0.01,
      status: 'success',
      timestamp: '2026-10-01T21:11:15Z',
    },
    {
      id: 'tr-04',
      traceId: 'trace-autogen-1205',
      framework: 'autogen',
      agentId: 'consensus-validator',
      cloudRegion: 'us-west-2',
      action: 'State Quorum Consensus Check',
      promptTokens: 3200,
      completionTokens: 450,
      estimatedCostUsd: 0.0112,
      latencyMs: 420,
      confidenceScore: 0.92,
      driftVariance: 0.08,
      status: 'success',
      timestamp: '2026-10-01T21:11:40Z',
    },
  ],
  defaultPolicy: {
    operatingMode: 'autonomous',
    maxSpendPerMinuteUsd: 45.0,
    p99LatencyCutoffMs: 850,
    confidenceFloor: 0.85,
    circuitBreakerTripped: false,
    updatedAt: '2026-10-01T21:00:00Z',
  },
  operationsDeck: {
    badge: '04 // Fleet Governance',
    title: 'Operational Telemetry &',
    titleHighlight: 'Policy Safeguards',
    subtitle: 'Live trace telemetry, circuit-breaker thresholds, and multi-agent fleet policy enforcement.',
    adminButtonText: 'Governance Controls',
  },
});
