import { TelemetryConfig, TelemetryConfigSchema } from '@/types/telemetry';

export const telemetryConfig: TelemetryConfig = TelemetryConfigSchema.parse({
  refreshIntervalMs: 2500,
  kpiPulses: [
    {
      id: 'kpi-p99-latency',
      name: 'Global Mesh Latency',
      value: 12.6,
      formattedValue: '12.6 ms',
      unit: 'ms',
      changePercentage24h: -14.8,
      targetBenchmark: 20.0,
      severity: 'optimal',
      trend: 'down',
    },
    {
      id: 'kpi-agent-throughput',
      name: 'Autonomous Throughput',
      value: 2.15,
      formattedValue: '2.15M ops/s',
      unit: 'M ops/s',
      changePercentage24h: 38.4,
      targetBenchmark: 1.5,
      severity: 'optimal',
      trend: 'up',
    },
    {
      id: 'kpi-consensus-drift',
      name: 'State Mesh Consistency',
      value: 99.999,
      formattedValue: '99.999%',
      unit: '%',
      changePercentage24h: 0.001,
      targetBenchmark: 99.99,
      severity: 'optimal',
      trend: 'stable',
    },
    {
      id: 'kpi-active-agents',
      name: 'Active Distributed Agents',
      value: 8600,
      formattedValue: '8,600 units',
      unit: 'units',
      changePercentage24h: 18.2,
      targetBenchmark: 5000,
      severity: 'optimal',
      trend: 'up',
    },
  ],
  efficiencyGains: [
    {
      category: 'Pipeline Autonomous Orchestration',
      headlineMetric: '92% Reduction in Manual Interventions',
      savingsRatio: '14.2x Faster Mean Time To Resolution (MTTR)',
      hoursAutomatedPerWeek: 1680,
      costReductionPercentage: 64.5,
      humanInterventionDrop: 92.0,
      description: 'Dynamic graph re-planning eliminates blocking deadlocks across edge compute pods.',
    },
    {
      category: 'Compute & Resource Optimization',
      headlineMetric: '43% Cloud Cost Optimization',
      savingsRatio: '$1.48M Annualized Compute Savings',
      hoursAutomatedPerWeek: 840,
      costReductionPercentage: 43.2,
      humanInterventionDrop: 88.5,
      description: 'Predictive token allocation routes batch tasks to lowest marginal cost carbon-neutral hubs.',
    },
  ],
  initialEvents: [
    {
      id: 'evt-001',
      timestamp: '2026-09-29T20:20:10.112Z',
      sourceHub: 'hub-tyo-01',
      eventCategory: 'agent_dispatch',
      message: 'Agent pool #382 synchronized state root across 4 peer hubs.',
      status: 'success',
      latencyMs: 14.1,
    },
    {
      id: 'evt-002',
      timestamp: '2026-09-29T20:20:45.342Z',
      sourceHub: 'hub-fra-01',
      eventCategory: 'pipeline_sync',
      message: 'Consensus quorum reached for workflow batch 0x9AF8.',
      status: 'success',
      latencyMs: 11.7,
    },
    {
      id: 'evt-003',
      timestamp: '2026-09-29T20:21:05.901Z',
      sourceHub: 'hub-dhk-01',
      eventCategory: 'state_transition',
      message: 'Edge gateway ingress auto-scaled to handle spike (+45 Gbps).',
      status: 'info',
      latencyMs: 21.9,
    },
    {
      id: 'evt-004',
      timestamp: '2026-09-29T20:21:28.450Z',
      sourceHub: 'hub-sfo-01',
      eventCategory: 'failover_recovery',
      message: 'Worker thread re-routed to Tokyo hub seamlessly without dropped frames.',
      status: 'success',
      latencyMs: 8.3,
    },
  ],
});
